server {
    listen 80;
    server_name _;
    root /var/www/public;

    index index.php index.html;

    charset utf-8;

    # Logs
    access_log  /var/log/nginx/agrofinance_access.log;
    error_log   /var/log/nginx/agrofinance_error.log;

    # Assets statiques (Vite build)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp)$ {
        expires max;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Toutes les requetes vers index.php (Laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Securite : interdire l'acces aux fichiers .env et .git
    location ~ /\.(env|git|htaccess) {
        deny all;
    }

    location ~ \.php$ {
        fastcgi_pass   app:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include        fastcgi_params;
        fastcgi_read_timeout 300;
    }
}
